# GAS08: ¿Cuál es el gasto comercial total de una actividad económica concreta en una región y periodo concretos?

PREFIX edintgast: <https://edint.es/def/cubo-gasto-comercial#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX edintdimension: <http://vocab.linkeddata.es/datosabiertos/def/dimension#>
PREFIX edintmeasure: <http://vocab.linkeddata.es/datosabiertos/def/measure#>

SELECT (SUM(?amount) AS ?totalExpenditure)
WHERE {
  ?obs a qb:Observation ;
       qb:dataSet edintgast:dataset1 ;
       edintdimension:refAdminRegion ?region ;
       edintdimension:refPeriod ?period ;
       edintdimension:economicActivity ?activity ;
       edintmeasure:expenditureAmount ?amount .

  FILTER(?region = <http://vocab.linkeddata.es/datosabiertos/recurso/territorio/municipio/zaragoza>)
  FILTER(?period = <https://example.org/interval/2025-01>)
  FILTER(?activity = <http://lod.ine.es/kos/cnae/CNAE-2025/G>)
}
